# Javascript Node CircleCI 2.0 configuration file

version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9.2

    working_directory: ~

    steps:
      - checkout

      # Install dependencies
      - run: npm --prefix install
      
      # run tests
      - run: npm --prefix test

  deployement:
    docker:
      - image: circleci/node:9.2

    working_directory: ~

    steps:
      - checkout
     
workflows:
  version: 2
  build_and_test:
    jobs:
     - test
     - deployement:
         requires:
           - test