# Javascript Node CircleCI 2.0 configuration file

version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9.2

    working_directory: ~

    steps:
      - checkout

      # Install dependencies
      - run: npm install
      
      # run tests
      - run: npm test

  deployement:
    docker:
      - image: circleci/node:9.2

    working_directory: ~

    steps:
      - checkout
    # Add ssh key to enable the communication with AWS
      - add_ssh_keys:
          fingerprints:
            - "08:26:82:fb:1e:21:05:80:eb:7b:bb:cb:17:73:4a:d8"
      
      # Deploy on AWS
        # Construct tarball
      - run: tar -cvf SwelloDesk.tar ~/

        # Compute checksum
      - run: md5sum SwelloDesk.tar > SwelloDesk.chksum

        # Import src files and checksum to AWS
      - run: scp -r -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no SwelloDesk.tar SwelloDesk.chksum ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com:.

        # Check checksum of tarball
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com md5sum -c SwelloDesk.chksum

        # Stop and delete actual server
      - run: (ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com pm2 stop server || true) && sleep 1
      - run: (ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com pm2 delete server || true) && sleep 1
      - run: (ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com pm2 delete start || true) && sleep 1

        # Clean AWS directory
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com rm -rf software-engineering-CS673  || true
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com rm SwelloDesk.chksum || true

        # Untar server and delete tarball
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com tar -xvf SwelloDesk.tar
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com rm SwelloDesk.tar || true
      
        # Install server
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com npm install
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com npm --prefix frontend/ install

      #Change localhost to correct address and port
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com myip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com result="ec2-${myip//[.]/-}.eu-west-3.compute.amazonaws.com"
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com echo -e "HOST=${result}" >> /home/ec2-user/software-engineering-CS673/frontend/.env
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com sudo sed -i -e "s/localhost/${result}/g" /home/ec2-user/software-engineering-CS673/frontend/package.json
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com sudo sed -i -e "s/localhost/${result}/g" /home/ec2-user/software-engineering-CS673/frontend/src/socket/config.js
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com sudo sed -i -e "s/localhost/${result}/g" /home/ec2-user/software-engineering-CS673/frontend/src/components/chat/Chat.js
     
        # Start server 
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com pm2 start server.js && sleep 1
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com pm2 save
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com pm2 start frontend/node_modules/react-scripts/scripts/start.js && sleep 1
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-35-181-151-203.eu-west-3.compute.amazonaws.com pm2 save


     
workflows:
  version: 2
  build_and_test:
    jobs:
     - test
     - deployement:
         requires:
           - test